from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.domain.entities.role import Role


class RoleRepository(Protocol):

    def list_all(self) -> Sequence[Role]: ...
    def get_by_id(self, role_id: UUID, /) -> Role | None: ...

    def get_by_name(self, name: str) -> Role | None: ...
    def add(self, role: Role) -> None: ...
    def update(self, role: Role) -> None: ...

    def delete(self, entity: Role) -> None: ...
