"""add authenticated_at to auth sessions

Revision ID: dd4b86e84bf3
Revises: ecf2b1ef03ca
Create Date: 2026-10-05 22:29:15.166499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dd4b86e84bf3"
down_revision: Union[str, Sequence[str], None] = "ecf2b1ef03ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "auth_sessions",
        sa.Column(
            "authenticated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.execute("""
        UPDATE auth_sessions
        SET authenticated_at = created_at
        WHERE authenticated_at IS NULL
        """)

    op.alter_column(
        "auth_sessions",
        "authenticated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_sessions", "authenticated_at")
    # ### end Alembic commands ###
