"""add cascade delete to auth sessions user fk

Revision ID: ecf2b1ef03ca
Revises: 169671ba0c13
Create Date: 2026-09-21 20:21:51.101030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf2b1ef03ca'
down_revision: Union[str, Sequence[str], None] = '169671ba0c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_sessions_user_id_fkey'), 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'auth_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('auth_sessions_user_id_fkey'), 'auth_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
